class Harf {
  int id;
  String tavsif;
  String harf;
  List<String> misollar;
  List<String> uzbekchaUqilishi; // Yangi maydon

  Harf({
    required this.id,
    required this.tavsif,
    required this.harf,
    required this.misollar,
    required this.uzbekchaUqilishi, // Yangi maydon
  });

  factory Harf.fromJson(Map<String, dynamic> json) {
    return Harf(
      id: json['id'],
      tavsif: json['tavsif'],
      harf: json['harf'],
      misollar: List<String>.from(json['misollar']),
      uzbekchaUqilishi:
          List<String>.from(json['uzbekchaUqilishi']), // Yangi maydon
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'tavsif': tavsif,
      'harf': harf,
      'misollar': misollar,
      'uzbekchaUqilishi': uzbekchaUqilishi, // Yangi maydon
    };
  }
}

final List<Harf> harflar = [
  {
    "id": 1,
    "tavsif": "Alif harfi so'z boshida bog'lanadi.",

    "harf": "ا",
    "misollar": [
      "اَ",
      "اِ",
      "اُ",
      "رَ",
      "رِ",
      "رُ",
      "اَرْ",
      "اِرْ",
      "اُرْ",
    ],
    "uzbekchaUqilishi": [
      "A",
      "I",
      "U",
      "Ro",
      "Ri",
      "Ru",
      "Ar",
      "Ir",
      "Ur"
    ], // Yangi maydon
    "kirilchaUqilishi":[
    ]
  },
  {
    "id": 2,
    "tavsif":
        "Za harfi so'z boshida va ortasida bog'lanadi. so'z oxirda bog'lanmaydi.",
    "harf": "ز",
    "misollar": [
      "زَ",
      "زِ",
      "زُ",
      "أَزْ",
      "اِزْ",
      "اُزْ",
      "زَرْ",
      "زِرْ",
      "زُرْ",
      "اَزْرُ",
      "اِزْرُ",
      "اُزْرُ",
      "اُرْزُ"
    ],
    "uzbekchaUqilishi": [
      "Za",
      "Zi",
      "Zu",
      "Az",
      "Iz",
      "Uz",
      "Zar",
      "Zir",
      "Zur",
      "Azru",
      "Izru",
      "Uzru",
      "Urzu"
    ] // Yangi maydon
  },
  {
    "id": 3,
    "tavsif": "Mim harfi hama holatda bog'lanadi",
    "harf": "م",
    "misollar": [
      "مَ",
      "مِ",
      "مُ",
      "اَمْ",
      "اِمْ",
      "اُمْ",
      "مُرْ",
      "مُزْ",
      "رُمْ",
      "اَمَرَ",
      "اُمِرَ",
      "اَمْرُ",
      "اِمْرُ",
      "رَمْزُ",
      "اِرْمِ",
      "مَرْمَرْ",
      "رَمْرَمْ",
      "زَمْزَمْ"
    ],
    "uzbekchaUqilishi": [
      "Ma",
      "Mi",
      "Mu",
      "Am",
      "Im",
      "Um",
      "Mur",
      "Muz",
      "Rum",
      "Amara",
      "Umira",
      "Amru",
      "Imru",
      "Ramzu",
      "Irmi",
      "Marmar",
      "Ramram",
      "Zamzam"
    ] // Yangi maydon
  },
  {
    "id": 4,
    "tavsif": "Ta harfi hama holatda bog'lanadi",
    "harf": "ت",
    "misollar": [
      "تَ",
      "تِ",
      "تُ",
      "مَتْ",
      "مِتْ",
      "مُتْ",
      "تَمَرْ",
      "تَرِرْ",
      "زُرْتَ",
      "اَمَرْتِ",
      "مَرَرْتُ",
      "اُمِرْتُ",
      "اَمَرَتْ",
      "اَمَرْتُمْ",
      "أُمِرْتُمْ",
      "مَرَرْتُمْ"
    ],
    "uzbekchaUqilishi": [
      "Ta",
      "Ti",
      "Tu",
      "Mat",
      "Mit",
      "Mut",
      "Tamar",
      "Tarir",
      "Zurta",
      "Amarti",
      "Marartu",
      "Umirtu",
      "Amartat",
      "Amartum",
      "Umirtum",
      "Marartum"
    ] // Yangi maydon
  },
  {
    "id": 5,
    "tavsif": "Nun harfi hama holatda bog'lanadi",
    "harf": "ن",
    "misollar": [
      "نَ",
      "نِ",
      "نُ",
      "اِنْ",
      "زِرْ",
      "مَنْ",
      "مِنْ",
      "نَمْ",
      "اَنْتَ",
      "نِمْتَ",
      "اَنْتُمْ",
      "نِمْتُمْ",
      "نَزِرُ",
      "نَزِنُ",
      "اَمَرْنَ",
      "اُمِرْنَ",
      "مَرَرْنَ",
      "اَمْرَرْنَ"
    ],
    "uzbekchaUqilishi": [
      "Na",
      "Ni",
      "Nu",
      "In",
      "Zir",
      "Man",
      "Min",
      "Nam",
      "Anta",
      "Nimta",
      "Antum",
      "Nimtum",
      "Naziru",
      "Nazinu",
      "Amarna",
      "Umirna",
      "Mararna",
      "Amrarna"
    ] // Yangi maydon
  },
  {
    "id": 6,
    "tavsif": "Ya harfi hama holatda bog'lanadi",
    "harf": "ي",
    "misollar": [
      "يَ",
      "يِ",
      "يُ",
      "اَيْ",
      "اَيْمُ",
      "زَيْتُ",
      "مَيْتُ",
      "رَاَيْ",
      "رَمْيُ",
      "يَمَنْ",
      "مَرْيَمْ",
      "مَيْЗَرْ",
      "مَيْمَنْ",
      "اَيْمَنْ",
      "اَمَرَيْنِ",
      "زَيْتَيْنِ",
      "اَيْمَيْنِ",
      "مَيْتَيْنِ"
    ],
    "uzbekchaUqilishi": [
      "Ya",
      "Yi",
      "Yu",
      "Ay",
      "Aymu",
      "Zaytu",
      "Maytu",
      "Raay",
      "Ramyu",
      "Yaman",
      "Maryam",
      "Mayzar",
      "Mayman",
      "Ayman",
      "Amaraayni",
      "Zaytayni",
      "Aymayni",
      "Maytayni"
    ] // Yangi maydon
  },
  {
    "id": 7,
    "tavsif": "Ba harfi hama holatda bog'lanadi",
    "harf": "ب",
    "misollar": [
      "بَ",
      "بِ",
      "بُ",
      "اَبْ",
      "اِبْنُ",
      "بِنْتُ",
      "بَيْتُ",
      "بَيْنُ",
      "رَيْبُ",
      "زَيْنَبْ",
      "بَرْبَرْ",
      "بَيْرَمْ",
      "اَبْرَمْ",
      "مِنْبَرْ",
      "بِاَمْرَيْنِ",
      "بِبَيْتَيْنِ",
      "مِنْبَرَيْنِ",
      "زَيْنَبَيْنِ"
    ],
    "uzbekchaUqilishi": [
      "Ba",
      "Bi",
      "Bu",
      "Ab",
      "Ibnu",
      "Bintu",
      "Baytu",
      "Baynu",
      "Raybu",
      "Zaynab",
      "Barbar",
      "Bayram",
      "Abram",
      "Minbar",
      "Bi'amrayni",
      "Bibaytayni",
      "Minbarayni",
      "Zaynabayni"
    ] // Yangi maydon
  },
  {
    "id": 8,
    "tavsif": "Kaf harfi hama holatda bog'lanadi",
    "harf": "ك",
    "misollar": [
      "كَ",
      "كِ",
      "كُ",
      "كَمْ",
      "كُمْ",
      "كُنْ",
      "كَيْ",
      "بَكْرُ",
      "مَكْرُ",
      "كَرْمُ",
      "كَنْزُ",
      "تَرْكُ",
      "كَتَبَ",
      "يَكْتُبُ",
      "تَرَكَ",
      "يَتْرُكُ",
      "كَتَبْتُمْ",
      "اَمَرَكَ",
      "اَمَرَتْكَ",
      "كُنْتُ",
      "مُمْكِنْ"
    ],
    "uzbekchaUqilishi": [
      "Ka",
      "Ki",
      "Ku",
      "Kam",
      "Kum",
      "Kun",
      "Kay",
      "Bakru",
      "Makru",
      "Karmu",
      "Kanzu",
      "Tarku",
      "Kataba",
      "Yaktubu",
      "Taraka",
      "Yatruku",
      "Katabtum",
      "Amaraaka",
      "Amaratka",
      "Kuntu",
      "Mumkin"
    ] // Yangi maydon
  },
  {
    "id": 9,
    "tavsif": "Lam harfi so'z boshida, ortasida va oxirida bog'lanadi.",
    "harf": "ل",
    "misollar": [
      "لَ",
      "لِ",
      "لُ",
      "ال",
      "بال",
      "لم",
      "لُن",
      "كل",
      "نَزَلَ",
      "لاَزِمَ",
      "كَمُلَ",
      "أَنزَلَ",
      "اَلزَمَ",
      "أَكْمَلَ",
      "أَكَلَت",
      "أَكَلْنَا",
      "أَكَلْتَ",
      "أَكَلْتِ",
      "أَكَلْتُ",
      "أَكَلْتُمْ",
      "بُلْبُل",
      "يَعْلَمْلَم",
      "تَزَلْزَلَ",
      "تَزَلْزَلَ",
      "يَتَزَلْزَلُ",
      "مُتَزَلْزِل"
    ],
    "uzbekchaUqilishi": [
      "La",
      "Li",
      "Lu",
      "Al",
      "Bal",
      "Lam",
      "Lun",
      "Kul",
      "Nazala",
      "Lazima",
      "Kamula",
      "Anzala",
      "Alzama",
      "Akmala",
      "Akalat",
      "Akalna",
      "Akalta",
      "Akalti",
      "Akaltu",
      "Akaltum",
      "Bulbul",
      "Ya'lamlam",
      "Tazalzala",
      "Tazalzala",
      "Yatazalzalu",
      "Mutazalzil"
    ] // Yangi maydon
  },
  {
    "id": 10,
    "tavsif": "Vov harfi so'z o'rtasida va oxirida bog'lanmaydi.",
    "harf": "و",
    "misollar": [
      "وَ",
      "وِ",
      "وُ",
      "اَوْ",
      "رَوْ",
      "نَوْ",
      "لَوْ",
      "وَرَمْ",
      "وَتَرْ",
      "وَمَنْ",
      "وَلَنْ",
      "وَلَمْ",
      "وَكَمْ",
      "اَوْلُ",
      "رَوْمُ",
      "يَوْمُ",
      "كَوْنُ",
      "وَيْلُ",
      "وَزْنُ",
      "كَوْكَبْ",
      "مَوْكِبْ",
      "اَوْلَمْتُمْ",
      "اَوْتَرْتُمْ"
    ],
    "uzbekchaUqilishi": [
      "Va",
      "Vi",
      "Vu",
      "Av",
      "Rov",
      "Nav",
      "Lav",
      "Varom",
      "Vatar",
      "Vaman",
      "Valan",
      "Valam",
      "Vakam",
      "Avlu",
      "Rovmu",
      "Yavmu",
      "Kavnu",
      "Vaylu",
      "Vaznu",
      "Kavkab",
      "Mavkib",
      "Avlamtum",
      "Avtartum"
    ],
    "kirilchaUqilishi": [
      "Ва",
      "Ви",
      "Ву",
      "Ав",
      "Ров",
      "Нав",
      "Лав",
      "Варом",
      "Ватар",
      "Ваман",
      "Валан",
      "Валам",
      "Вакам",
      "Авлу",
      "Ровму",
      "Явму",
      "Кавну",
      "Вайлу",
      "Вазну",
      "Кавкаб",
      "Мавкиб",
      "Авламтум",
      "Автартум"
    ]
  },
  {
    "id": 11,
    "tavsif": "Harf va harakatlar bilan tuzilgan misollar.",
    "harf": "ه",
    "misollar": [
      "هَ",
      "هِ",
      "هُ",
      "هَبْ",
      "هَمْ",
      "هَلْ",
      "هُوَ",
      "هِيَ",
      "هُمْ",
      "زُهْ",
      "اَهَمْ",
      "وَهَبَ",
      "لَهَبْ",
      "وَهَمْ",
      "لَهُمْ",
      "بِهِمْ",
      "مِنْهُ",
      "مِنْهُمْ",
      "اِلَيْهِ",
      "اِلَيْهِمْ",
      "اَمْهِلْهُمْ"
    ],
    "uzbekchaUqilishi": [
      "Ha",
      "Hi",
      "Hu",
      "Hab",
      "Ham",
      "Hal",
      "Huva",
      "Hiya",
      "Hum",
      "Zuh",
      "Aham",
      "Vahab",
      "Lahab",
      "Vaham",
      "Lahum",
      "Bihim",
      "Minhu",
      "Minhum",
      "Ilayhi",
      "Ilayhim",
      "Amhilhum"
    ],
    "kirilchaUqilishi": [
      "Ҳа",
      "Ҳи",
      "Ҳу",
      "Ҳаб",
      "Ҳам",
      "Ҳал",
      "Ҳува",
      "Ҳия",
      "Ҳум",
      "Зуҳ",
      "Аҳам",
      "Ваҳаб",
      "Лаҳаб",
      "Ваҳам",
      "Лаҳум",
      "Биҳим",
      "Минҳу",
      "Минҳум",
      "Илайҳи",
      "Илайҳим",
      "Амҳилҳум"
    ]
  },
  {
    "id": 12,
    "tavsif": "Fa harfi va boshqa so'zlar misollar bilan.",
    "harf": "ف",
    "misollar": [
      "فَ",
      "فِ",
      "فُ",
      "فَمْ",
      "فَنْ",
      "كَفْ",
      "فَلَكْ",
      "كَفَنْ",
      "نَفَرْ",
      "فَوْرُ",
      "فَوْزُ",
      "فَهْمُ",
      "فِكْرُ",
      "زِفْرُ",
      "كِفْلُ",
      "فُلْفُلْ",
      "نَفَرْ",
      "نَفَلْ",
      "فَهِمَ",
      "يَفْهَمُ",
      "اِفْهَمِ",
      "اِفْتَتَنَ",
      "يَفْتَتِنُ",
      "اِفْتَرَكَ",
      "يَفْتَكِرُ"
    ],
    "uzbekchaUqilishi": [
      "Fa",
      "Fi",
      "Fu",
      "Fam",
      "Fan",
      "Kaf",
      "Falak",
      "Kafan",
      "Nafar",
      "Favru",
      "Favzu",
      "Fahmu",
      "Fikru",
      "Zifru",
      "Kiflu",
      "Fulful",
      "Navfar",
      "Navfal",
      "Fahima",
      "Yafhamu",
      "Ifhami",
      "Iftatana",
      "Yaftatinu",
      "Iftaroka",
      "Yaftakiru"
    ],
    "kirilchaUqilishi": [
      "Фа",
      "Фи",
      "Фу",
      "Фам",
      "Фан",
      "Каф",
      "Фалак",
      "Кафан",
      "Нафар",
      "Фавру",
      "Фавзу",
      "Фаҳму",
      "Фикру",
      "Зифру",
      "Кифлу",
      "Фулфул",
      "Навфар",
      "Навфал",
      "Фаҳима",
      "Яфҳаму",
      "Ифҳами",
      "Ифтатана",
      "Яфтатину",
      "Ифтарока",
      "Яфтакиру"
    ]
  },
  {
    "id": 13,
    "tavsif": "Qaf harfi va boshqa murakkab so'zlar misollar bilan.",
    "harf": "ق",
    "misollar": [
      "قَ",
      "قِ",
      "قُ",
      "زُقْ",
      "قِنْ",
      "قُلْ",
      "قُمْ",
      "قِفْ",
      "قِهْ",
      "قَلْبُ",
      "قَبْلُ",
      "فَوْقُ",
      "قَلَمْ",
      "قَمَرْ",
      "لَقَبْ",
      "قُمْقُمْ",
      "اِقْتَرَبَ",
      "يَقْتَرِبُ",
      "اِنْقَلَبَ",
      "يَنْقَلِبُ",
      "كَمَالْ-قَمَرْ",
      "فَلَكْ-فَلَقْ",
      "فَرْكُ-فَرْقُ"
    ],
    "uzbekchaUqilishi": [
      "Qo",
      "Qi",
      "Qu",
      "Zuq",
      "Qin",
      "Qul",
      "Qum",
      "Qif",
      "Qih",
      "Qolbu",
      "Qoblu",
      "Favqu",
      "Qolam",
      "Qomar",
      "Laqob",
      "Qumqum",
      "Iqtaro'ba",
      "Yaqtaribu",
      "Inqolaba",
      "Yanqolibu",
      "Kamal-Qomar",
      "Falak-Falaq",
      "Farku-Farqu"
    ],
    "kirilchaUqilishi": [
      "Қо",
      "Қи",
      "Қу",
      "Зуқ",
      "Қин",
      "Қул",
      "Қум",
      "Қиф",
      "Қиҳ",
      "Қолбу",
      "Қоблу",
      "Фавқу",
      "Қолам",
      "Қомар",
      "Лақоб",
      "Қумқум",
      "Иқтароба",
      "Яқтарибу",
      "Инқолаба",
      "Янқолибу",
      "Камал-Қомар",
      "Фалак-Фалақ",
      "Фарку-Фарқу"
    ]
  },
  {
    "id": 14,
    "tavsif": "Shin harfi va murakkab so'zlar misollar bilan.",
    "harf": "ش",
    "misollar": [
      "شَ",
      "شِ",
      "شُ",
      "رُشْ",
      "بُشْ",
      "شَرْ",
      "شَقْ",
      "شَمْ",
      "شَكْ",
      "بِشْرُ",
      "شِرْبُ",
      "شَهْرُ",
      "نَشْرُ",
      "شُكْرُ",
      "شُرْبُ",
      "مَشْرُبْ",
      "مَشْرِبْ",
      "مَشْرِقْ",
      "مُشْتَهِرْ",
      "مُشْتَرَكْ",
      "اِشْتَهَرَ",
      "يَشْتَهِرُ",
      "اِبْرُنْشَقُ",
      "يَبْرُنْشِقُ"
    ],
    "uzbekchaUqilishi": [
      "Sha",
      "Shi",
      "Shu",
      "Rosh",
      "Bush",
      "Shar",
      "Shaq",
      "Sham",
      "Shak",
      "Bishru",
      "Shirbu",
      "Shahru",
      "Nashru",
      "Shukru",
      "Shurbu",
      "Mashrob",
      "Mashrib",
      "Mashriq",
      "Mushtahir",
      "Mushtarok",
      "Ishtaharo",
      "Yashtahiru",
      "Ibronshaqo",
      "Yabronshiqu"
    ],
    "kirilchaUqilishi": [
      "Ша",
      "Ши",
      "Шу",
      "Рош",
      "Буш",
      "Шар",
      "Шақ",
      "Шам",
      "Шак",
      "Бишру",
      "Ширбу",
      "Шаҳру",
      "Нашру",
      "Шукру",
      "Шурбу",
      "Машроб",
      "Машриб",
      "Машриқ",
      "Муштаҳир",
      "Муштарок",
      "Иштаҳаро",
      "Яштаҳиру",
      "Иброншақо",
      "Яброншиқу"
    ]
  },
  {
    "id": 15,
    "tavsif": "Sin harfi va murakkab so'zlar misollar bilan.",
    "harf": "س",
    "misollar": [
      "سَ",
      "سِ",
      "سُ",
      "بَسْ",
      "سَمْ",
      "سِرْ",
      "سِنْ",
      "سِلْ",
      "سَفَرْ",
      "سَقَرْ",
      "سَبَقْ",
      "سَلَفْ",
      "سَمَكْ",
      "فَرَسْ",
      "مَسْلَكْ",
      "مَسْكَنْ",
      "مُسْلِمْ",
      "مُشْرِكْ",
      "سِمْسِمْ",
      "أَسْلَمَ",
      "يُسْلِمُ",
      "اِسْتَيْسَرَ",
      "يَسْتَيْسِرُ"
    ],
    "uzbekchaUqilishi": [
      "Sa",
      "Si",
      "Su",
      "Bas",
      "Sam",
      "Sir",
      "Sin",
      "Sil",
      "Safar",
      "Saqor",
      "Sabaq",
      "Salaf",
      "Samak",
      "Faros",
      "Maslak",
      "Maskan",
      "Muslim",
      "Mushriq",
      "Simsim",
      "Aslama",
      "Yuslimu",
      "Istaysaro",
      "Yastaysiru"
    ],
    "kirilchaUqilishi": [
      "Са",
      "Си",
      "Су",
      "Бас",
      "Сам",
      "Сир",
      "Син",
      "Сил",
      "Сафар",
      "Сақор",
      "Сабақ",
      "Салаф",
      "Самак",
      "Фарос",
      "Маслак",
      "Маскан",
      "Муслим",
      "Мушрик",
      "Симсим",
      "Аслама",
      "Юслиму",
      "Истайсаро",
      "Ястайсиру"
    ]
  },
  {
    "id": 16,
    "tavsif": "ث harfi bilan bog'langan misollar va o'qilishlari.",
    "harf": "ث",
    "misollar": [
      "ثَ",
      "ثِ",
      "ثُ",
      "بَثْ",
      "ثِبْ",
      "ثَمْ",
      "ثِنْ",
      "ثَمَرْ",
      "ثَمَنَ",
      "ثَوْرُ",
      "ثَوْبُ",
      "ثَيْبُ",
      "مِثْلُ",
      "مُثْلُ",
      "مَثَلْ",
      "كَوْثَرْ",
      "أَكْثَرُ",
      "يُكْثِرُ",
      "أَثْبَتَ",
      "يُثْبِتُ",
      "اِسْتَكْثَرَ",
      "يَسْتَكْثِرُ",
      "اِسْتَثْقَلَ",
      "يَسْتَثْقِلُ",
      "سَمَرْ-ثَمَرْ",
      "سَبْتُ-ثَبْتُ",
      "سَلْمُ-ثَلْمُ"
    ],
    "uzbekchaUqilishi": [
      "Sa",
      "Si",
      "Su",
      "Bas",
      "Sib",
      "Sam",
      "Sin",
      "Samar",
      "Saman",
      "Savru",
      "Savbu",
      "Saybu",
      "Misl",
      "Musl",
      "Masal",
      "Kavsar",
      "Aksar",
      "Yuksiru",
      "Asbata",
      "Yusbitu",
      "Istaksaro",
      "Yastaksiru",
      "Istasqola",
      "Yastasqilu",
      "Samar-Samar",
      "Sabtu-Sabtu",
      "Salmu-Salmu"
    ],
    "kirilchaUqilishi": [
      "Са",
      "Си",
      "Су",
      "Бас",
      "Сиб",
      "Сам",
      "Син",
      "Самар",
      "Саман",
      "Савру",
      "Савбу",
      "Сайбу",
      "Мисл",
      "Мусл",
      "Масал",
      "Кавсар",
      "Аксар",
      "Юксиру",
      "Асбата",
      "Юсбиту",
      "Истаксаро",
      "Ястаксиру",
      "Истасқола",
      "Ястасқилу",
      "Самар-Самар",
      "Сабту-Сабту",
      "Салму-Салму"
    ]
  },
  {
    "id": 17,
    "tavsif": "Sod harfi bilan bog'langan qo'shimcha misollar va o'qilishlari.",
    "harf": "ص",
    "misollar": [
      "صَ",
      "صِ",
      "صُ",
      "صُمَ",
      "صِفْ",
      "فَصْ",
      "صُرُوفْ",
      "صَبَرْ",
      "بَصَرْ",
      "قَصَبْ",
      "نَصَرَ",
      "يَنْصُرُ",
      "اِسْتَبْصَرَ",
      "يَسْتَبْصِرُ",
      "صَفَرْ-صَفَرْ",
      "صَيْفُ-صَيْفُ",
      "اِنْتَصَبَ-اِنْتَصَبَ"
    ],
    "uzbekchaUqilishi": [
      "So",
      "Si",
      "Su",
      "Sum",
      "Sif",
      "Fas",
      "Sorof",
      "Sobar",
      "Basor",
      "Qosob",
      "Nasoro",
      "Yansuru",
      "Istabsoro",
      "Yastabsiru",
      "Safar-Sofar",
      "Sayfu-Soyfu",
      "Intasaba-Intasoba"
    ],
    "kirilchaUqilishi": [
      "Со",
      "Си",
      "Су",
      "Сум",
      "Сиф",
      "Фас",
      "Сороф",
      "Собар",
      "Басор",
      "Қособ",
      "Насоро",
      "Янсуру",
      "Истабсоро",
      "Ястабсиру",
      "Сафар-Софар",
      "Сайфу-Сойфу",
      "Интасаба-Интасоба",
    ]
  },
  {
    "id": 18,
    "tavsif": "To harfi so'z boshida, o'rtasida va oxirida bog'lanadi.",
    "harf": "ط",
    "misollar": [
      "طَ",
      "طِ",
      "طُ",
      "طَالَ",
      "طَوْ",
      "شَطْ",
      "بَطْ",
      "قَطْ",
      "فَطَ",
      "وَطَنْ",
      "طُلَبْ",
      "طُرُفْ",
      "طُهْرُ",
      "طِفْلُ",
      "مَطَرْ",
      "مَطْلَبْ",
      "مَسْقَطْ",
      "مَوْطِنْ",
      "مَرْبِطْ",
      "اِسْتَطْبَرَ",
      "يَسْتَطْبِرُ",
      "اِسْتَوْطَنَ",
      "يَسْتَوْطِنُ",
      "طَرَفْ-طُرُفْ",
      "سَبْطُ-سَبْطُ",
      "مُسْتَطِرْ-مُسْتَطِرْ"
    ],
    "uzbekchaUqilishi": [
      "To",
      "Ti",
      "Tu",
      "Tol",
      "Toy",
      "Shat",
      "Bat",
      "Qot",
      "Faqot",
      "Vaton",
      "Tolab",
      "Torof",
      "Tuhru",
      "Tiflu",
      "Mator",
      "Matlob",
      "Masqot",
      "Mavtin",
      "Marbit",
      "Istobaro",
      "Yastobiru",
      "Istavtona",
      "Yastavtinu",
      "Tarof-Torof",
      "Sabtu-Sabtu",
      "Mustatir-Mustatir"
    ],
    "kirilchaUqilishi": [
      "То",
      "Ти",
      "Ту",
      "Тол",
      "Той",
      "Шат",
      "Бат",
      "Қот",
      "Фақот",
      "Ватон",
      "Толаб",
      "Тороф",
      "Туҳру",
      "Тифлу",
      "Матор",
      "Матлоб",
      "Масқот",
      "Мавтин",
      "Марбит",
      "Истобаро",
      "Ястобиру",
      "Иставтона",
      "Яставтину",
      "Тароф-Тороф",
      "Сабту-Сабту",
      "Мустатир-Мустатир"
    ]
  }
].map((json) => Harf.fromJson(json)).toList();
